version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: smartwallet-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartwallet
    volumes:
      - smartwallet_pgdata:/var/lib/postgresql/data

volumes:
  smartwallet_pgdata:
